config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'search', to: 'pages#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end

	def about
	end

	def search
    if !params[:user].nil?
      @username = params[:user][:name]
      @username.strip
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">
      Copyright &copy; 25 Most Recent Tweets by <a href="https://github.com/henrylou">Hengyu Lou</a>
    </p>
  </div>
  <!-- /.container -->
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <!-- <a class="navbar-brand" href="#">Start Bootstrap</a> -->
    <%= link_to 'Home', root_path, class: 'navbar-brand' %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav mr-auto">
        <!-- <li class="nav-item active">
          <a class="nav-link" href="#">Home
            <span class="sr-only">(current)</span>
          </a>
        </li> -->
        <li class="nav-item">
          <!-- <a class="nav-link" href="#">About</a> -->
          <%= link_to 'About', about_path, class: 'nav-link' %>
        </li>
       
      </ul>
      <div class="form-inline my-2 my-lg-0">
        <!-- <input class="form-control mr-sm-2" type="text" placeholder="Search"> -->
        <!-- <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button> -->
        <%= form_for :user, url: search_path, method: "get" do |f| %>
          <%= f.text_field :name, type: 'text', placeholder: 'Twitter handle', class: "form-control mr-sm-2" %>
          <%= f.button 'Submit', type: 'submit', class: "btn btn-secondary my-2 my-sm-0" %> 
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>25 Most Recent Tweets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= favicon_link_tag asset_path('favicon.png'), :rel => 'icon', :type =>  'image/png' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="content"><%= yield %></div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="about-bg">
  <div class="container mt-5">
    <h2 class="text-center">About</h2>
    <div class="row mt-5">
      <div class="col"></div>
      <div class="shadow-lg p-3 mb-5 bg-white rounded col-7">This web app takes a user's Twitter handle and displays that user's 25 most recent tweets.</div>
      <div class="col"></div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<header>
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <!-- <li data-target="#carouselExampleIndicators" data-slide-to="2"></li> -->
    </ol>
    <div class="carousel-inner" role="listbox">
      <!-- Slide One - Set the background image for this slide in the line below -->
      <div class="carousel-item active home1">
        <div class="carousel-caption" style="top: 30%; bottom: auto; color: black">
          <h1 class="display-4">25 Most Recent Tweets of a Twitter Handle</h1>
          <p class="lead center d-none d-md-block">Please type in a twitter handle to find the 25 most recent tweets</p>
        </div>
      </div>
      <!-- Slide Two - Set the background image for this slide in the line below -->
      <div class="carousel-item home2">
        <div class="carousel-caption" style="top: 25%; bottom: auto; color: black">
          <h3>Try the twitter web app right now!</h3>
          <p class="d-none d-md-block">Let's find out what your friend is posting on twitter</p>
        </div>
      </div>
      <!-- Slide Three - Set the background image for this slide in the line below -->
      <!-- <div class="carousel-item" style="background-image: url('http://placehold.it/1900x1080')">
        <div class="carousel-caption d-none d-md-block">
          <h3>Third Slide</h3>
          <p>This is a description for the third slide.</p>
        </div>
      </div> -->        
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</header>

<!-- Page Content -->
<section class="py-5">
  <div class="container">
    <h3>25 Most Recent Tweets of a Twitter Handle</h3>
    <p>
      This web app takes a user's <code>Twitter handle</code> and displays that user's <code>25 most recent tweets.</code>
    </p>
  </div>
</section>

app/views/pages/search.html.erb
<div class="search-bg">
	<% begin %>
		<% CLIENT.user(@username) %>

	<% rescue %>	
		<div class="container mt-5">
	    <h2 class="text-center">I am sorry!</h2>
	    <div class="row mt-5">
	      <div class="col"></div>
	      <div class="shadow-lg p-3 mb-5 bg-white rounded col-7">This user handle does not exist!</div>
	      <div class="col"></div>
	    </div>
	  </div>
	<% else %>
		<% begin %>
			<% tweets = CLIENT.user_timeline(@username, count: 25) %>
		<% rescue%>	
			<div class="row">
				<div class="col"></div>
				<div class="shadow-lg p-3 mb-5 bg-white rounded col-7">There is something wrong with this user handle!</div>
				<div class="col"></div>
			</div>
		<% else %>
			<div class="row mt-3">
				<div class="col"></div>
				<div class="col text-center"><h4><%= @username %></h4></div>
				<div class="col"></div>
			</div>
			<% tweets.each do |tweet| %>
				<div class="row">
					<div class="col"></div>
					<div class="shadow-lg p-3 mb-5 bg-white rounded col-7"><%= tweet.text %></div>
					<div class="col"></div>
				</div>
			<% end %>
		<% end %>
	<% end %>
</div> 